[package]
name = "deltafall-clicker"
version = "0.1.0"
edition = "2024"

[dependencies]
colors-transform = "0.2.11"
lerp = "0.5.0"
macroquad = {version = "0.4.13", features = ["audio"]}
wasm = "0.0.0"
